services:
  backend:
    build: ./server
    image: jandeman12345/videomerger-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/outputs:/app/outputs
      - ./server/thumbnails:/app/thumbnails
  frontend:
    build: ./merger
    image: jandeman12345/videomerger-frontend:latest
    ports:
      - "4173:4173"
    depends_on:
      - backend